apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
  labels:
    app: immich
data:
  DB_HOSTNAME: "immich-postgres"
  REDIS_HOSTNAME: "immich-redis"
  TZ: "Asia/Taipei"
