apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  namespace: immich
  labels:
    app: immich
    component: redis
spec:
  type: ClusterIP
  selector:
    app: immich
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
