apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
  namespace: immich
  labels:
    app: immich
type: Opaque
stringData:
  DB_PASSWORD: "changeme-please"
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"
