apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: immich
  labels:
    app: immich
    component: postgres
spec:
  type: ClusterIP
  selector:
    app: immich
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
