#!/command/with-contenv bash
# shellcheck shell=bash

usermod -o -u "${PUID:-911}" abc &>/dev/null
groupmod -o -g "${PGID:-911}" abc &>/dev/null

echo "
╔══════════════════════════════════════════════════════════════╗

░██████░███     ░███ ░███     ░███ ░██████  ░██████  ░██     ░██
  ░██  ░████   ░████ ░████   ░████   ░██   ░██   ░██ ░██     ░██
  ░██  ░██░██ ░██░██ ░██░██ ░██░██   ░██  ░██        ░██     ░██
  ░██  ░██ ░████ ░██ ░██ ░████ ░██   ░██  ░██        ░██████████
  ░██  ░██  ░██  ░██ ░██  ░██  ░██   ░██  ░██        ░██     ░██
  ░██  ░██       ░██ ░██       ░██   ░██   ░██   ░██ ░██     ░██
░██████░██       ░██ ░██       ░██ ░██████  ░██████  ░██     ░██

  Woow Immich - Home Assistant Add-on by WOOWTECH
  Fork of fabio-garavini/hassio-addons (HTTP-only for LAN)
  Immich & Machine Learning from Image Genius
╠══════════════════════════════════════════════════════════════╣
  User/Group ID:
  User UID: $(id -u abc)
  User GID: $(id -g abc)
╚══════════════════════════════════════════════════════════════╝"

chown abc:abc \
    /data \
    /config \
    /defaults